[package]
name = "sol-program-counter-native-rust-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bytemuck_derive = "=1.8.1"
borsh = "1.5.6"
borsh-derive = "1.5.6"
solana-program = "1.18.26"
